### ISSUE TITLE
Design proposal: Identify links in languages that differ to the page

### ISSUE THREAD

**Issue by borisschapira** [HTTPArchive/almanac.httparchive.org#1781]
## Target pages

Mostly translations, I guess.

## Objectives

Allow users and navigation tools to anticipate the change in language mid-navigation.
Prevent users from being taken to pages whose language they don’t understand.

([Opquast Checklist BP 126](https://checklists.opquast.com/en/qualiteweb/the-main-language-of-a-links-target-page-is-provided-if-different-from-the-original-page))

## Screenshots Before / After (one visual lead, others are possible)

![Capture d’écran 2020-12-16 à 22 03 43](https://user-images.githubusercontent.com/284742/102407239-0f82e380-3fec-11eb-8fa2-07ca7320c437.png)

![Capture d’écran 2020-12-16 à 22 08 36](https://user-images.githubusercontent.com/284742/102407289-275a6780-3fec-11eb-9a3c-eec0da853f31.png)

**Comment by bazzadp** [comment]
This is actually pretty easy to do @borisschapira if the translators are willing to add an `hreflang` to each link not in the translations language (including changing from markdown link to HTML link).

Then it's a simple manner of adding the following CSS (|I'm assuming the only links will be in English)

```css
a[hreflang="en"]::after {
  content: '(en)/English';
  content: '(en)';
  vertical-align: super;
  font-size: 0.6em;
}
```

Looks like this:

![Screenshot](https://user-images.githubusercontent.com/10931297/102411521-f5e09c80-3fe9-11eb-8059-db0dc45865c0.png)

Wanna play about with this and if happy then submit a pull request for it?

**Comment by borisschapira** [comment]
And if you want a simple rule for all languages:

```
[hreflang]::after {
  content: 'attr(hreflang)';
  vertical-align: super;
  font-size: 0.6em;
}
```

But I don't know if it's compatible with the current design (line heights?) or how to make this accessible (do we need to hide this from assistive tech?).

**Comment by bazzadp** [comment]
Very nice! Slight improvements by adding parenthesis:

```css
[hreflang]::after {
  content: '(' attr(hreflang) ')';
  vertical-align: super;
  font-size: 0.6em;
}
```

Seems to work fine in Chrome, Safari and Firefox.

Not too worried about line-height changes and no I wouldn't hide it from AT - no reason they wouldn't want to know this too. My original design did use the `/` notion to give a different message to AT (English) but that doesn't work in your general solution and [support of it isn't great anyway (Chromium only)], and not sure we should use the English version of English anyway.

I'd be happy to accept this into the codebase. Though I do think it's a lot to ask translators for yet another thing to add. Still have no issue using it for those translators that wanna got the extra mile. Or do you think it could lead to expectations being set if it's only half-used?

Maybe as a follow on, we could automate to auto set the hreflang in translations, either by assuming it's `en` if no explicit `hreflang` and making exceptions for certain sites known to translate (MDN and Wikipedia) if the URL contains that language (e.g. `/fr/` for French). Could also strip out the `hreflang` in those cases where it matches the translation language to prevent this showing in error.

Anyway I'm OK to accept this in.

**Comment by rviscomi** [comment]
Is there a more passive solution where we use a regex attribute selector to see if en-US exists in the `href`attribute? For example:

```css
a[href*="en-US"] {
  ...
}
```

**Comment by bazzadp** [comment]
This catches a lot. Not everything, but a lot:

```css
/* Auto set language highlighter on translations for known English sites */
html:not([lang="en"]) [href*="/en-US/"]::after,
html:not([lang="en"]) [href*="/en/"]::after,
html:not([lang="en"]) [href^="https://web.dev"]::after,
html:not([lang="en"]) [href^="https://v8.dev"]::after,
html:not([lang="en"]) [href^="https://developers.google.com"]::after {
  content: '(en)';
  vertical-align: super;
  font-size: 0.6em;
}

/* Set language highlighter when hreflang is used (should only be used when different lang) */
[hreflang]::after {
  content: '(' attr(hreflang) ')';
  vertical-align: super;
  font-size: 0.6em;
}
```

**Comment by borisschapira** [comment]
I'm not sure about the first part. Some of thoses sites exist in languages other than English (https://web.dev/pl/ for example). It would be necessary to check that future authors do not point to those versions… I'm afraid that this will result in a lot of maintenance.

**Comment by bazzadp** [comment]
Wasn’t aware they had translated content. Ok then maybe just first three lines as they should be pretty safe? The first part is just a fallback for those that haven’t implemented hreflang.

**Comment by bazzadp** [comment]
@HTTPArchive/translators any comments on this? Would this be useful and if so would you use it when translating? Any alternatives suggestions?

**Comment by hijuliancode** [comment]
I'm starting with translation, I think that's useful, I would use it.

**Comment by noah-vdv** [comment]
Sure I could see it being useful and it's not that big a deal to add it. I'm just confused as to which version of the code needs to be added

**Comment by bazzadp** [comment]
So, to be clear we would be adding this CSS:

```css
/* Set language highlighter when hreflang is used (should only be used when different lang) */
[hreflang]::after {
  content: '(' attr(hreflang) ')';
  vertical-align: super;
  font-size: 0.6em;
}
```

This would mean any translator adding an `hreflang="en"` attribute to a language would get the extra UI to show this is a link in another language.

This would be a good bit of extra effort for the translators to add that that attribute to every link especially when it's a markdown link instead of an HTML link as have to convert (maybe we should update the English versions?). To make it a little bit easier, we will also add this CSS:

```css
/* Auto set language highlighter on translations for known English sites */
html:not([lang="en"]) [href*="/en-US/"]::after,
html:not([lang="en"]) [href*="/en/"]::after,
html:not([lang="en"]) [href^="https://en."]::after {
  content: '(en)';
  vertical-align: super;
  font-size: 0.6em;
}
```

This would mean every MDN and wikipedia link (for an example), would **automatically** get the UI - without any effort from the Translators. This would happen if the language is not English `html:not([lang="en"])` but the URL contains an English-like part. So this saves some effort for the translators as they won't have to add the `hreflang` attributes to these links. It also means the current translations automatically get some of these bits of UI. It won't catch everything but we do use MDN and Wikipedia a fair bit, and the risk is small, so a good thing to add in my opinion to make live a little easier.
