### ISSUE TITLE
Whitespace broken in markdown metadata

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#258]
The "Third Parties" chapter has this yaml:

```yaml
part_number: II
chapter_number: 5
title: Third Parties
authors: [patrickhulce]
reviewers: [simonhearne, flowlabs, jasti, zeman]
```

When this is processed, the generated template includes this metadata:

```
{% set metadata = {"part_number":"II","chapter_number":5,"title":"Third
Parties","authors":["patrickhulce"],"reviewers":["simonhearne"," flowlabs","
jasti"," zeman"]} %}
```

Note the line break between the title "Third" and "Parties". And also the whitespace before `flowlabs` and `jasti`.

This is causing the `get_chapter_image_dir` method to fail to generate the correct image directory for the chapter because where it expects a space character it's encountering a newline.

![image](https://user-images.githubusercontent.com/1120896/67879577-99839a80-fb13-11e9-8081-0ee256337849.png)

The generated URL is `/static/images/2019/05_ThirdParties/hero_lg.jpg` but it should be `http://127.0.0.1:8080/static/images/2019/05_Third_Parties/hero_lg.jpg`.

This is also manifesting itself oddly in the markup, although it still renders correctly:

```html
<title>
Third
Parties | 2019 | The Web Almanac by HTTP Archive
</title>
```

The reviewer names should also be trimmed during the generation.
