### ISSUE TITLE
Deploy a static / content-less version of the website

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#260]
The production website at almanac.httparchive.org has only been deployed once, and it's currently just a placeholder announcement with a link to this repo.

In preparation for launch next ~week I'd like to deploy a current version of the website with only the following pages:

- home
- contributors
- methodology
- table of contents

All content like chapter pages and the featured chapter on the home page should be omitted. These omissions shouldn't be merged into master, so a separate "pre-launch" branch should be used.

As of now the only way to spot UX bugs is to run the website locally. In an effort to get the QA process started, an early deploy will help get more eyes on the UX and bugs filed.

**Comment by rviscomi** [comment]
🎉 The website is live at https://almanac.httparchive.org/en/2019/

**Comment by rviscomi** [comment]
One important note for future deployments.

`app.yaml` has a required change to work in Python 3.7 App Engine environments:

```yaml
runtime: python37
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
```

The `script` property must be set to `auto`.
